CALL INSERT_FUNCIONARIO('0','0','0','0','0','ESTOQUISTA')

SELECT ABRE_CAIXA('0,00')


SELECT * FROM CAIXA

CALL INSERT_VENDA('AS','AS','T',0,FALSE,'AS')

SELECT * FROM venda

CALL INSERT_PRODUTO('TANYCLI', 'BLUSA', '16,99')